info:
  app:
    name: account-core
    description: account core neoris application
    version: 1.0.0
    encoding: UTF-8
    java:
      version: 1.11.0

spring:
  profile: dev
  datasource:
    url: jdbc:postgresql://${DB_URL}:5432/neoris1
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    flyway:
      baselineOnMigrare: true
      createSchemas: true
      locations: db/migration, db/specific/h2
    account:
      url: jdbc:postgresql://${DB_URL}:5432/neoris2
      username: postgres
      password: 1234
      migration:
        location: db/account
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true #LazyLoading
        current_session_context_class: thread #LazyLoading
        jdbc:
          lob:
            non_contextual_creation: true #Ignore CLOB creation